Repository goravel/framework, pull requests merged in 2023-08, with the labels that each got.

#255 feat: Add testing feature
  README.md
  README_zh.md
  contracts/database/orm/factory.go
  contracts/database/orm/mocks/Factory.go
  contracts/foundation/container.go
  contracts/foundation/mocks/Application.go
  contracts/testing/testing.go
  database/console/migrate.go
  database/console/migrate_fresh_command_test.go
  database/console/migrate_rollback_command_test.go
  database/factory.go
  database/factory_test.go
  database/gorm/mocks/Initialize.go
  database/gorm/test_utils.go
  database/gorm/wire_interface.go
  facades/testing.go
  foundation/application.go
  foundation/console/stubs.go
  foundation/console/test_make_command.go
  foundation/console/test_make_command_test.go
  foundation/container.go
  log/logger/daily.go
  log/logger/single.go
  mail/application_test.go
  queue/application_test.go
  support/constant.go
  support/docker/docker.go
  support/docker/redis.go
  testing/application.go
  testing/docker/database.go
  testing/docker/database_test.go
  testing/docker/docker.go
  testing/docker/docker_test.go
  testing/docker/mysql.go
  testing/docker/mysql_test.go
  testing/docker/postgresql.go
  testing/docker/postgresql_test.go
  testing/docker/sqlite.go
  testing/docker/sqlite_test.go
  testing/docker/sqlserver.go
  testing/docker/sqlserver_test.go
  testing/service_provider.go
  testing/test_case.go
  testing/test_case_test.go
Labels: 🚀 Review Ready

#259 fix: [#229] media file not parsing correctly
  validation/validator.go
  validation/validator_test.go
Labels: 🚀 Review Ready

#260 chore: Optimize carbon structure
  support/carbon/carbon.go
  support/carbon/constants.go
Labels: 🚀 Review Ready

#261 workflow(test): update go 1.21
  .github/workflows/test.yml
Labels: 🚀 Review Ready

#198 refactor: http and route
  auth/auth_test.go
  contracts/http/response.go
  contracts/route/mocks/Engine.go
  contracts/route/mocks/Route.go
  filesystem/file_test.go
  foundation/application_test.go
  foundation/container.go
  go.mod
  go.sum
  http/gin_context.go
  http/gin_context_test.go
  http/gin_request.go
  http/gin_response.go
  http/limit/limit.go
  http/middleware/cors.go
  http/middleware/opentracing.go
  http/middleware/throttle.go
  http/middleware/tls.go
  http/service_provider.go
  route/gin.go
  route/gin_group.go
  route/gin_group_test.go
  route/gin_test.go
  route/route.go
  route/service_provider.go
  route/test_ca.crt
  route/test_ca.key
  route/utils.go
  route/utils_test.go
Labels: 🚀 Review Ready, ❗ Breaking Change

#265 feat: add InputArray and InputMap
  contracts/http/mocks/Request.go
  contracts/http/request.go
Labels: ✏️ Feature, 🚀 Review Ready

#268 feat: Add throttle middleware
  http/middleware/throttle.go
  http/middleware/throttle_test.go
  http/service_provider.go
Labels: 🚀 Review Ready

#269 feat: Move grpc middleware to goravel/example, reduce the dependency of third packages
  go.mod
  grpc/middleware/opentracing.go
Labels: 🚀 Review Ready

#254 feat: custom database connection for model
  contracts/database/orm/mocks/Association.go
  contracts/database/orm/mocks/Transaction.go
  contracts/database/orm/orm.go
  database/gorm/event.go
  database/gorm/event_test.go
  database/gorm/query.go
  database/gorm/query_test.go
  database/gorm/test_utils.go
  database/gorm/transaction.go
  database/orm.go
Labels: 🚀 Review Ready

#273 feat: Limit support for template
  contracts/foundation/container.go
  contracts/foundation/mocks/Application.go
  contracts/http/mocks/View.go
  contracts/http/response.go
  contracts/http/view.go
  database/gorm/test_utils.go
  facades/http.go
  foundation/container.go
  http/middleware/throttle_test.go
  http/service_provider.go
  http/view.go
  http/view_test.go
Labels: 🚀 Review Ready

#275 feat: Upgarde the carbon package
  database/gorm/query_test.go
  go.mod
  go.sum
  support/carbon/carbon.go
  support/carbon/json.go
Labels: 🚀 Review Ready

#277 fix: [#239] [Bug] The JWT token will be expired immediately when ttl == 0
  auth/auth.go
  auth/auth_test.go
Labels: 🚀 Review Ready

#279 chore: Rename route
  contracts/foundation/container.go
  contracts/foundation/mocks/Application.go
  contracts/route/mocks/Engine.go
  contracts/route/mocks/Route.go
  contracts/route/mocks/Router.go
  contracts/route/route.go
  facades/route.go
  foundation/application_test.go
  foundation/container.go
  route/route.go
Labels: 🚀 Review Ready

#282 fix: will panic when model contains a private field
  database/gorm/event.go
  database/gorm/event_test.go
  database/gorm/query.go
  database/gorm/query_test.go
  database/gorm/utils.go
  database/gorm/utils_test.go
  support/database/database.go
  support/database/database_test.go
Labels: 🚀 Review Ready
