Repository goravel/framework, pull requests merged in 2023-06, with the labels that each got.

#160 file.Create adds error return
  auth/console/policy_make_command.go
  config/application_test.go
  console/console/make_command.go
  database/console/migrate_command_test.go
  database/console/migrate_creator.go
  database/console/migrate_creator_test.go
  database/console/migrate_make_command.go
  database/console/model_make_command.go
  database/console/observer_make_command.go
  event/console/event_make_command.go
  event/console/listener_make_command.go
  filesystem/application_test.go
  http/console/controller_make_command.go
  http/console/middleware_make_command.go
  http/console/request_make_command.go
  queue/console/job_make_command.go
  queue/task_test.go
  support/file/file.go
  support/file/file_test.go
  validation/console/rule_make_command.go
Labels: Review Ready

#159 Feat: [#49] Support Package Development
  auth/service_provider.go
  cache/service_provider.go
  config/application.go
  config/service_provider.go
  console/application.go
  console/application_test.go
  console/cli_context.go
  console/service_provider.go
  contracts/console/command.go
  contracts/console/command/command.go
  contracts/console/mocks/Context.go
  contracts/foundation/application.go
  contracts/foundation/container.go
  contracts/foundation/mocks/Application.go
  crypt/service_provider.go
  database/console/migrate_rollback_command.go
  database/service_provider.go
  event/application.go
  event/service_provider.go
  filesystem/service_provider.go
  foundation/application.go
  foundation/application_test.go
  foundation/console/vendor_publish_command.go
  foundation/console/vendor_publish_command_test.go
  foundation/container.go
  foundation/container_test.go
  foundation/service_provider.go
  grpc/service_provider.go
  hash/service_provider.go
  http/service_provider.go
  log/service_provider.go
  mail/application_test.go
  mail/service_provider.go
  queue/application.go
  queue/application_test.go
  queue/service_provider.go
  queue/worker.go
  route/service_provider.go
  schedule/service_provider.go
  support/file/file_test.go
  validation/service_provider.go
Labels: Review Ready

#162 Feat: Add make package command
  foundation/application.go
  foundation/console/package_make_command.go
  foundation/console/package_make_command_stubs.go
  foundation/console/package_make_command_test.go
Labels: Review Ready

#163 Feat: vendor:publish command supports publish directory
  foundation/console/vendor_publish_command.go
  foundation/console/vendor_publish_command_test.go
Labels: Review Ready

#167 Fix: [#148][#150]
  schedule/application.go
  schedule/application_test.go
  schedule/support/event.go
  schedule/support/event_test.go
  support/constant.go
Labels: Review Ready

#169 Feat: Split filesystem disk
  filesystem/application.go
  filesystem/application_test.go
  filesystem/cos.go
  filesystem/minio.go
  filesystem/oss.go
  filesystem/s3.go
  filesystem/utils.go
  go.mod
  go.sum
Labels: Review Ready

#168 Fix: [#139] Optimize HTTP print
  route/gin.go
Labels: Review Ready

#172 Feat: Remove redis driver for Cache module
  cache/driver.go
  cache/driver_test.go
  cache/memory_test.go
  cache/redis.go
Labels: Review Ready

#175 Feat: Optimize cache custom driver
  cache/application.go
  cache/driver.go
  cache/driver_test.go
  cache/service_provider.go
Labels: Review Ready

#179 Add step option to the migrate refresh command
  database/console/migrate_refresh_command.go
  database/console/migrate_refresh_command_test.go
  database/console/migrate_rollback_command.go
  database/console/migrate_rollback_command_test.go
  database/console/model_make_command_test.go
  database/console/observer_make_command_test.go
Labels: Review Ready

#176 feat: make command add subdirectories support
  auth/console/policy_make_command.go
  auth/console/policy_make_command_test.go
  auth/console/policy_stubs.go
  console/console/make_command.go
  console/console/make_command_test.go
  console/console/stubs.go
  database/console/model_make_command.go
  database/console/model_make_command_test.go
  database/console/observer_make_command.go
  database/console/observer_make_command_test.go
  database/console/stubs.go
  event/console/event_make_command.go
  event/console/event_make_command_test.go
  event/console/event_stubs.go
  event/console/listen_stubs.go
  event/console/listener_make_command.go
  event/console/listener_make_command_test.go
  http/console/controller_make_command.go
  http/console/controller_make_command_test.go
  http/console/middleware_make_command.go
  http/console/middleware_make_command_test.go
  http/console/request_make_command.go
  http/console/request_make_command_test.go
  http/console/stubs.go
  queue/console/job_make_command.go
  queue/console/job_make_command_test.go
  queue/console/job_stubs.go
  support/str/str.go
  support/str/str_test.go
  validation/console/rule_make_command.go
  validation/console/rule_make_command_test.go
  validation/console/stubs.go
Labels: enhancement, Review Ready

#180 feat: update dependabot label
  .github/dependabot.yml
Labels: 🚀 Review Ready, 🚨 High Priority

#188 Fix: Validation should ignore when a field is empty and is not required
  validation/validation_test.go
  validation/validator.go
Labels: 🚀 Review Ready

#189 Feat: Add New* for Carbon
  support/carbon/json.go
Labels: 🚀 Review Ready

#192 fix: path error in Windows
  auth/console/jwt_secret_command.go
  console/console/key_generate_command.go
  filesystem/application_test.go
  filesystem/file.go
  filesystem/file_test.go
  filesystem/utils.go
  foundation/console/vendor_publish_command.go
  foundation/console/vendor_publish_command_test.go
  foundation/path.go
  http/gin_request.go
  log/logger/daily.go
  log/logrus_writer.go
  route/gin_test.go
  support/file/file.go
Labels: ☢️ Bug, 🚀 Review Ready

#194 feat: remove promptui
  console/console/key_generate_command.go
  console/console/key_generate_command_test.go
  foundation/console/package_make_command.go
  foundation/console/vendor_publish_command.go
  go.mod
  go.sum
  support/constant.go
  support/path/path.go
Labels: 🚀 Review Ready

#199 Fix: MakeGate error
  cache/driver.go
  database/gorm/query_test.go
  database/gorm/test_utils.go
  filesystem/application.go
  foundation/application_test.go
  foundation/console/package_make_command_stubs.go
  foundation/container.go
  support/constant.go
  testing/docker/docker.go
  testing/docker/redis.go
Labels: 🚀 Review Ready

#202 Upgrade v1.12.3
  .github/workflows/test.yml
  auth/console/policy_make_command_test.go
  config/application_test.go
  console/console/key_generate_command_test.go
  console/console/make_command_test.go
  database/console/migrate_command_test.go
  database/console/migrate_creator_test.go
  database/console/migrate_fresh_command_test.go
  database/console/migrate_make_command_test.go
  database/console/migrate_refresh_command_test.go
  database/console/migrate_reset_command_test.go
  database/console/migrate_rollback_command_test.go
  database/console/migrate_status_command_test.go
  database/console/model_make_command_test.go
  database/console/observer_make_command_test.go
  database/gorm/query_test.go
  database/gorm/test_utils_test.go
  database/orm_test.go
  event/console/event_make_command_test.go
  event/console/listener_make_command_test.go
  filesystem/application_test.go
  filesystem/file_test.go
  foundation/application.go
  foundation/application_test.go
  foundation/console/package_make_command.go
  foundation/console/package_make_command_test.go
  http/console/controller_make_command_test.go
  http/console/middleware_make_command_test.go
  http/console/request_make_command_test.go
  log/logrus_writer_test.go
  mail/application_test.go
  queue/application_test.go
  queue/console/job_make_command_test.go
  queue/task_test.go
  support/constant.go
  support/file/file.go
  support/file/file_test.go
  support/path/path_test.go
  validation/console/rule_make_command_test.go
Labels: 🚀 Review Ready

#213 feat: use sonic to json serializing and deserializing
  crypt/aes.go
  go.mod
  go.sum
  http/gin_request.go
  log/formatter/general.go
  route/gin_test.go
  support/carbon/json_test.go
Labels: 🚀 Review Ready

#214 Feat: Fix throttle middleware panic
  http/service_provider.go
  support/constant.go
Labels: 🚀 Review Ready

#185 feat: Database Seeding Functionality
  contracts/database/seeder/mocks/Facade.go
  contracts/database/seeder/seeder.go
  contracts/foundation/container.go
  contracts/foundation/mocks/Application.go
  database/console/migrate_fresh_command.go
  database/console/migrate_fresh_command_test.go
  database/console/migrate_refresh_command.go
  database/console/migrate_refresh_command_test.go
  database/console/seed_command.go
  database/console/seed_command_test.go
  database/console/seeder_make_command.go
  database/console/seeder_make_command_test.go
  database/console/stubs.go
  database/seeder.go
  database/seeder_test.go
  database/service_provider.go
  facades/seeder.go
  foundation/application_test.go
  foundation/container.go
  testing/mock/mock.go
Labels: ✏️ Feature, 🛠 In Progress

#216 workflow(all): optimize workflow
  .github/workflows/check-pr-title.yml
  .github/workflows/codecov.yml
  .github/workflows/cr.yml
  .github/workflows/filesystem.yml
  .github/workflows/lint.yml
  .github/workflows/mail.yml
  .github/workflows/test.yml
  .github/workflows/welcome.yml
Labels: 🚀 Review Ready

#218 fix: auth to return error when user doesn't exists
  auth/auth.go
  auth/auth_test.go
Labels: 🚀 Review Ready

#219 feat: Optimize facades.Cache().Remember method
  cache/driver_test.go
  cache/memory.go
  cache/memory_test.go
  contracts/cache/cache.go
  contracts/cache/mocks/Cache.go
  contracts/cache/mocks/Driver.go
Labels: 🚀 Review Ready

#220 workflow: optimize cr and title check
  .github/workflows/cr.yml
  .github/workflows/pr-check-title.yml
Labels: 🚀 Review Ready

#221 docs: optimize README
  README.md
  README_zh.md
Labels: 🚀 Review Ready

#223 workflow: optimize dependabot
  .github/dependabot.yml
Labels: 🚀 Review Ready
