Repository goravel/framework, pull requests merged in 2023-05, with the labels that each got.

#114 feat: Add Host method
  contracts/http/request.go
  http/gin_request.go
Labels: enhancement, Review Ready

#116 Fix middleware bug
  go.mod
  go.sum
  route/gin_group.go
  route/gin_group_test.go
Labels: bug, Review Ready

#121 Fix: [#136] Fix input bind conflict
  http/gin_context.go
  http/gin_request.go
  route/gin_test.go
  support/constant.go
Labels: Review Ready

#126 feat: add dependabot
  .github/dependabot.yml
  .github/workflows/codecov.yml
  .github/workflows/filesystem.yml
  .github/workflows/lint.yml
  .github/workflows/mail.yml
  .github/workflows/test.yml
  .github/workflows/welcome.yml
  event/application.go
Labels: enhancement, Review Ready

#132 feat: Update dependabot limit
  .github/dependabot.yml
Labels: enhancement, Review Ready
